# 📊 Reto 3 – Funciones y estadísticas en Pandas

**Objetivo:** aplicar funciones estadísticas y crear nuevas columnas basadas en cálculos.

In [7]:
import pandas as pd
datos = pd.read_csv('../data/4_resultados_agua.csv')

### 🔹 Ejemplo de función personalizada
Crea una función que clasifique el pH:

In [8]:
def clasificar_ph(valor):
    if valor < 6.5:
        return 'Ácido'
    elif valor <= 8.5:
        return 'Neutro'
    else:
        return 'Básico'

datos['categoria_ph'] = datos['pH'].apply(clasificar_ph)
datos.head()

  Punto   Temp    pH  OD_promedio categoria_ph
0     A  22.25  7.15          6.2       Neutro
1     B  24.30  7.20          5.8       Neutro
2     C  19.80  6.85          4.9       Neutro
3     D  23.65  7.05          6.5       Neutro
4     E  25.15  7.25          5.0       Neutro

### 💡 Actividad
- Calcula promedios de variables numéricas.
- Aplica al menos una función con `apply()` o `groupby()`.

In [9]:
# Tu código aquí import pandas as pd

datos = pd.read_csv('../data/4_resultados_agua.csv')

print(datos.describe())

media_temp = datos['Temp'].mean()
print(media_temp)

datos['Temp_Ajustada'] = datos['Temp'] - 0.5

datos['Indice_Calidad'] = datos['pH'] * datos['OD_promedio']

datos['Estado_Oxigeno'] = datos['OD_promedio'].apply(lambda x: 'Bueno' if x >= 5 else 'Malo')

datos.head()

            Temp        pH  OD_promedio
count   5.000000  5.000000     5.000000
mean   23.030000  7.100000     5.680000
std     2.093621  0.158114     0.712039
min    19.800000  6.850000     4.900000
25%    22.250000  7.050000     5.000000
50%    23.650000  7.150000     5.800000
75%    24.300000  7.200000     6.200000
max    25.150000  7.250000     6.500000
23.03

,Punto,Temp,pH,OD_promedio,Temp_Ajustada,Indice_Calidad,Estado_Oxigeno
0,A,22.25,7.15,6.2,21.75,44.330,Bueno
1,B,24.30,7.20,5.8,23.80,41.760,Bueno
2,C,19.80,6.85,4.9,19.30,33.565,Malo
3,D,23.65,7.05,6.5,23.15,45.825,Bueno
4,E,25.15,7.25,5.0,24.65,36.250,Bueno